services:
  - type: web
    name: quiz-app-java
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/helloworld-0.0.1-SNAPSHOT.jar"
    autoDeploy: true
